# IIPImage Dockerfile

FROM ubuntu:latest

# Install dependencies and IIPImage server
RUN apt-get update && apt-get install -y \
    iipimage-server \
    && rm -rf /var/lib/apt/lists/*

# Expose IIPImage's default port
EXPOSE 9000

COPY dirty.sh /dirty.sh
RUN chmod +x /dirty.sh
# Start the IIPImage server
CMD ["/dirty.sh"]